CREATE DATABASE IF NOT EXISTS `mydb`;
USE mydb; 
DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `otp`  VARCHAR(10) DEFAULT NULL,
  `contact` VARCHAR(15) NOT NULL,
  `password` VARCHAR(50) NOT NULL
  );